### ISSUE TITLE
Created an adaptation

### ISSUE THREAD

**Issue by mxashlynn** [Bananattack/omelette_font#1]
Hey!
Just wanted to let you know that I created [a small adaptation](https://github.com/mxashlynn/gb-studio-omelette-font) of a parts of Omelette for use with [GB Studio](https://github.com/chrismaltby/gb-studio).
Thanks for making and sharing these cool fonts!  🖋✨

**Comment by Bananattack** [comment]
Oh awesome! glad that it could be adapted for GB Studio, that's very cool to see these fonts in use there! ^^ Definitely makes sense to mix-and-match things like that to fit in the Game Boy's limited tileset! Let me know if you'd like your adaptation to be listed in the readme!

Hmm as an aside, I also wonder if GB Studio has a way to load new characters on the fly! That could be neat if it that could swap fonts out depending on the dialogue and draw it in letter-by-letter, similar to For the Frog The Bell Tolls. Then it could do a wider variety of characters by only loading what it needs to draw at the time. Even if not for this font, it would probably be a cool feature for it to have in their tool. (never tried GB Studio because I started doing homebrew before it existed, but it would be fun to try out for a gamejam or small project someday!)

**Comment by mxashlynn** [comment]
That's a cool idea!  I'm still using GB Studio 2 which can't do that, but 3 has been out for a while now and has many more font-related features so it's possible.

I'm also thinking of getting into roll-your-own style homebrew 😁
